version: "3.8"

services:
  php-apache:
    image: stdocker2901/php-sample:latest
    container_name: php_app
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_crud
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: Srujal7#5!4
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
