from . import ir_attachment
from . import school_subjects
from . import school_common
from . import school_student
from . import school_sports
from . import school_class
from . import school_teacher
from . import res_users
from . import school_student_reports
from . import school_student_attendance
